[workspace]
resolver = "2"
members = [
    "randomx-hash-calculator",
    "static-ccp",
]

[workspace.dependencies]

clap = { version = "4.5.1", features = ["derive"] }
rayon = "1.10.0"
rand = "0.8.5"
ccp-randomx = "0.8.0"
ccp-utils = "0.8.0"
ccp-shared = "0.8.0"