[package]
name = "rust-randomx-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
ccp-randomx = { version = "0.2.0", path = "../capacity-commitment-prover/crates/randomx" }
ccp-shared = "0.1.0"
clap = { version = "4.5.1", features = ["derive"] }
